'use server'

import { revalidatePath } from 'next/cache'
import { createServerSupabaseClient } from '@touracore/db'
import type {
  ReservationStatus,
  BookingSource,
  MealPlan,
  DocumentType,
} from '../types/database'
import { assertCurrentEntityAccess } from '../auth/access'
import { getCurrentOrg } from '../queries/auth'
import { updateGuest } from './guests'
import { fireAutomationTrigger } from '../stubs/automation/trigger-engine'
import { generateTouristTaxForReservation, logAdminAction } from './compliance'
import { syncAvailabilityForOrg } from '../stubs/integrations/channel-manager'
import { processPlatformChargeForReservation } from '../stubs/platform-billing/service'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CreateReservationData {
  entity_id: string
  guest_id: string
  room_id?: string | null
  room_type_id: string
  rate_plan_id?: string | null
  check_in: string
  check_out: string
  status?: ReservationStatus
  source?: BookingSource
  adults: number
  children?: number
  infants?: number
  pet_count?: number
  pet_details?: unknown[]
  meal_plan?: MealPlan
  total_amount?: number
  currency?: string
  commission_amount?: number
  commission_rate?: number
  channel_reservation_id?: string | null
  channel_confirmation_code?: string | null
  special_requests?: string | null
  internal_notes?: string | null
  group_id?: string | null
  group_name?: string | null
  created_by?: string | null
}

export interface UpdateReservationData {
  guest_id?: string
  room_id?: string | null
  room_type_id?: string
  rate_plan_id?: string | null
  check_in?: string
  check_out?: string
  status?: ReservationStatus
  source?: BookingSource
  adults?: number
  children?: number
  infants?: number
  pet_count?: number
  pet_details?: unknown[]
  meal_plan?: MealPlan
  total_amount?: number
  paid_amount?: number
  currency?: string
  commission_amount?: number
  commission_rate?: number
  special_requests?: string | null
  internal_notes?: string | null
  last_modified_by?: string | null
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const RESERVATION_PATHS = [
  '/dashboard',
  '/reservations',
  '/check-in',
  '/check-out',
  '/planning',
  '/finance',
]

function revalidateReservationPaths() {
  for (const p of RESERVATION_PATHS) {
    revalidatePath(p)
  }
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

/**
 * Create a new reservation.
 *
 * A reservation_code is generated by the database function
 * `generate_reservation_code`. We call it first, then insert.
 */
export async function createReservation(data: CreateReservationData) {
  if (!data.entity_id) throw new Error('entity_id is required')
  if (!data.guest_id) throw new Error('guest_id is required')
  if (!data.room_type_id) throw new Error('room_type_id is required')
  if (!data.check_in) throw new Error('check_in is required')
  if (!data.check_out) throw new Error('check_out is required')
  if (!data.adults || data.adults < 1) throw new Error('adults must be at least 1')

  await assertCurrentEntityAccess(data.entity_id)

  const supabase = await createServerSupabaseClient()

  // Generate reservation code via DB function
  const { data: codeResult, error: codeError } = await supabase.rpc(
    'generate_reservation_code',
    { org_id: data.entity_id }
  )
  if (codeError) throw new Error(`Failed to generate reservation code: ${codeError.message}`)

  // Auto-calculate commission from channel config if not explicitly provided
  let commissionRate = data.commission_rate ?? 0
  let commissionAmount = data.commission_amount ?? 0
  const source = data.source ?? 'direct'

  if (!commissionRate && !commissionAmount && source !== 'direct') {
    const { data: commissionConfig } = await supabase
      .from('channel_commissions')
      .select('commission_rate')
      .eq('entity_id', data.entity_id)
      .eq('channel', source)
      .single()

    if (commissionConfig) {
      commissionRate = commissionConfig.commission_rate
      commissionAmount = Math.round((data.total_amount ?? 0) * commissionConfig.commission_rate) / 100
    }
  }

  const { data: reservation, error } = await supabase
    .from('reservations')
    .insert({
      entity_id: data.entity_id,
      reservation_code: codeResult as string,
      guest_id: data.guest_id,
      room_id: data.room_id ?? null,
      room_type_id: data.room_type_id,
      rate_plan_id: data.rate_plan_id ?? null,
      check_in: data.check_in,
      check_out: data.check_out,
      status: data.status ?? 'confirmed',
      source,
      adults: data.adults,
      children: data.children ?? 0,
      infants: data.infants ?? 0,
      pet_count: data.pet_count ?? 0,
      pet_details: data.pet_details ?? [],
      meal_plan: data.meal_plan ?? 'room_only',
      total_amount: data.total_amount ?? 0,
      paid_amount: 0,
      currency: data.currency ?? 'EUR',
      commission_amount: commissionAmount,
      commission_rate: commissionRate,
      channel_reservation_id: data.channel_reservation_id ?? null,
      channel_confirmation_code: data.channel_confirmation_code ?? null,
      special_requests: data.special_requests ?? null,
      internal_notes: data.internal_notes ?? null,
      group_id: data.group_id ?? null,
      group_name: data.group_name ?? null,
      created_by: data.created_by ?? null,
    })
    .select()
    .single()

  if (error) throw new Error(`Failed to create reservation: ${error.message}`)

  try {
    await processPlatformChargeForReservation({
      organizationId: reservation.entity_id,
      reservationId: reservation.id,
      reservationCode: reservation.reservation_code,
      totalAmount: reservation.total_amount,
      status: reservation.status,
      source: reservation.source,
      createdAt: reservation.created_at,
    })
  } catch (platformBillingError) {
    console.error('[Reservation] Platform billing error post-create:', platformBillingError)
  }

  // Fire booking_confirmed automation (best-effort, non-blocking)
  fireAutomationTrigger('booking_confirmed', {
    organizationId: data.entity_id,
    reservationId: reservation.id,
  }).catch(() => {})

  // Push availability aggiornata ai canali OTA (best-effort, non-blocking)
  syncAvailabilityForOrg(data.entity_id).catch((err) =>
    console.error('[Reservation] Errore sync availability post-create:', err)
  )

  // Log the action
  logAdminAction({
    organizationId: data.entity_id,
    userId: data.created_by ?? undefined,
    action: 'reservation.create',
    entityType: 'reservation',
    entityId: reservation.id,
  }).catch(() => {})

  revalidateReservationPaths()
  return reservation
}

/**
 * Partially update a reservation.
 */
export async function updateReservation(id: string, data: UpdateReservationData) {
  if (!id) throw new Error('Reservation id is required')

  const supabase = await createServerSupabaseClient()
  const { property } = await getCurrentOrg()
  const orgId = property?.id

  let updateQuery = supabase
    .from('reservations')
    .update({
      ...data,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id)

  if (orgId) updateQuery = updateQuery.eq('entity_id', orgId)

  const { data: reservation, error } = await updateQuery
    .select()
    .single()

  if (error) throw new Error(`Failed to update reservation: ${error.message}`)

  if (data.status) {
    try {
      await processPlatformChargeForReservation({
        organizationId: reservation.entity_id,
        reservationId: reservation.id,
        reservationCode: reservation.reservation_code,
        totalAmount: reservation.total_amount,
        status: reservation.status,
        source: reservation.source,
        createdAt: reservation.created_at,
      })
    } catch (platformBillingError) {
      console.error('[Reservation] Platform billing error post-update:', platformBillingError)
    }
  }

  // Se le date sono cambiate, aggiorna availability sui canali
  if (data.check_in || data.check_out || data.status) {
    syncAvailabilityForOrg(reservation.entity_id).catch((err) =>
      console.error('[Reservation] Errore sync availability post-update:', err)
    )
  }

  revalidateReservationPaths()
  return reservation
}

/**
 * Cancel a reservation. Sets status to 'cancelled' and records the timestamp.
 */
export async function cancelReservation(id: string, reason?: string) {
  if (!id) throw new Error('Reservation id is required')

  const supabase = await createServerSupabaseClient()
  const { property } = await getCurrentOrg()
  const orgId = property?.id

  let cancelQuery = supabase
    .from('reservations')
    .update({
      status: 'cancelled' as ReservationStatus,
      cancelled_at: new Date().toISOString(),
      cancellation_reason: reason ?? null,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id)

  if (orgId) cancelQuery = cancelQuery.eq('entity_id', orgId)

  const { data: reservation, error } = await cancelQuery
    .select()
    .single()

  if (error) throw new Error(`Failed to cancel reservation: ${error.message}`)

  // Push availability aggiornata ai canali OTA (cancellazione libera disponibilita')
  syncAvailabilityForOrg(reservation.entity_id).catch((err) =>
    console.error('[Reservation] Errore sync availability post-cancel:', err)
  )

  // Log the action
  logAdminAction({
    organizationId: reservation.entity_id,
    action: 'reservation.cancel',
    entityType: 'reservation',
    entityId: reservation.id,
    details: reason ? { reason } : undefined,
  }).catch(() => {})

  revalidateReservationPaths()
  return reservation
}

/**
 * Data collected during the check-in wizard (documents + consents).
 */
export interface CheckInData {
  guest_id: string
  document_type?: DocumentType | null
  document_number?: string | null
  document_issued_by?: string | null
  document_expiry_date?: string | null
  privacy_consent: boolean
  marketing_consent: boolean
}

/**
 * Check in a reservation.
 * - Saves guest document info and consent flags.
 * - Sets status to 'checked_in' and records actual_check_in timestamp.
 * - Updates the assigned room status to 'occupied'.
 */
export async function checkInReservation(id: string, data?: CheckInData) {
  if (!id) throw new Error('Reservation id is required')

  const supabase = await createServerSupabaseClient()
  const { property } = await getCurrentOrg()
  const orgId = property?.id
  const now = new Date().toISOString()

  // Save guest document & consent data if provided
  if (data?.guest_id) {
    await updateGuest(data.guest_id, {
      document_type: data.document_type ?? null,
      document_number: data.document_number ?? null,
      document_issued_by: data.document_issued_by ?? null,
      document_expiry_date: data.document_expiry_date ?? null,
      privacy_consent: data.privacy_consent,
      privacy_consent_date: data.privacy_consent ? now : null,
      marketing_consent: data.marketing_consent,
      marketing_consent_date: data.marketing_consent ? now : null,
    })
  }

  // Update reservation
  let checkinQuery = supabase
    .from('reservations')
    .update({
      status: 'checked_in' as ReservationStatus,
      actual_check_in: now,
      updated_at: now,
    })
    .eq('id', id)

  if (orgId) checkinQuery = checkinQuery.eq('entity_id', orgId)

  const { data: reservation, error } = await checkinQuery
    .select()
    .single()

  if (error) throw new Error(`Failed to check in reservation: ${error.message}`)

  try {
    await processPlatformChargeForReservation({
      organizationId: reservation.entity_id,
      reservationId: reservation.id,
      reservationCode: reservation.reservation_code,
      totalAmount: reservation.total_amount,
      status: reservation.status,
      source: reservation.source,
      createdAt: reservation.created_at,
    })
  } catch (platformBillingError) {
    console.error('[CheckIn] Platform billing error post-check-in:', platformBillingError)
  }

  // Update room status to 'occupied' if a room is assigned
  if (reservation.room_id) {
    const { error: roomError } = await supabase
      .from('rooms')
      .update({ status: 'occupied', updated_at: now })
      .eq('id', reservation.room_id)
      .eq('entity_id', reservation.entity_id)

    if (roomError) {
      console.error(`Failed to update room status on check-in: ${roomError.message}`)
    }
  }

  // Generate tourist tax record (best-effort)
  generateTouristTaxForReservation(
    reservation.entity_id,
    reservation.id
  ).catch((err) => console.error('[CheckIn] Errore generazione tassa soggiorno:', err))

  // Fire checkin_day automation (best-effort)
  fireAutomationTrigger('checkin_day', {
    organizationId: reservation.entity_id,
    reservationId: reservation.id,
  }).catch(() => {})

  // Log the action
  logAdminAction({
    organizationId: reservation.entity_id,
    action: 'reservation.checkin',
    entityType: 'reservation',
    entityId: reservation.id,
  }).catch(() => {})

  revalidateReservationPaths()
  return reservation
}

/**
 * Check out a reservation.
 * - Sets status to 'checked_out' and records actual_check_out timestamp.
 * - Updates the assigned room status to 'cleaning'.
 * - Updates guest statistics (total_stays, total_nights, total_revenue, last_stay_date).
 */
export async function checkOutReservation(id: string) {
  if (!id) throw new Error('Reservation id is required')

  const supabase = await createServerSupabaseClient()
  const { property } = await getCurrentOrg()
  const orgId = property?.id
  const now = new Date().toISOString()

  // Update reservation
  let checkoutQuery = supabase
    .from('reservations')
    .update({
      status: 'checked_out' as ReservationStatus,
      actual_check_out: now,
      updated_at: now,
    })
    .eq('id', id)

  if (orgId) checkoutQuery = checkoutQuery.eq('entity_id', orgId)

  const { data: reservation, error } = await checkoutQuery
    .select()
    .single()

  if (error) throw new Error(`Failed to check out reservation: ${error.message}`)

  try {
    await processPlatformChargeForReservation({
      organizationId: reservation.entity_id,
      reservationId: reservation.id,
      reservationCode: reservation.reservation_code,
      totalAmount: reservation.total_amount,
      status: reservation.status,
      source: reservation.source,
      createdAt: reservation.created_at,
    })
  } catch (platformBillingError) {
    console.error('[CheckOut] Platform billing error post-check-out:', platformBillingError)
  }

  // Update room status to 'cleaning' if a room is assigned
  if (reservation.room_id) {
    const { error: roomError } = await supabase
      .from('rooms')
      .update({ status: 'cleaning', updated_at: now })
      .eq('id', reservation.room_id)
      .eq('entity_id', reservation.entity_id)

    if (roomError) {
      console.error(`Failed to update room status on check-out: ${roomError.message}`)
    }
  }

  // Update guest statistics
  if (reservation.guest_id) {
    const nights = Math.max(
      1,
      Math.round(
        (new Date(reservation.check_out).getTime() - new Date(reservation.check_in).getTime()) /
          (1000 * 60 * 60 * 24)
      )
    )

    // Fetch current guest stats
    const { data: guest } = await supabase
      .from('guests')
      .select('total_stays, total_nights, total_revenue')
      .eq('id', reservation.guest_id)
      .eq('entity_id', reservation.entity_id)
      .single()

    if (guest) {
      const { error: guestError } = await supabase
        .from('guests')
        .update({
          total_stays: (guest.total_stays ?? 0) + 1,
          total_nights: (guest.total_nights ?? 0) + nights,
          total_revenue: (guest.total_revenue ?? 0) + (reservation.paid_amount ?? 0),
          last_stay_date: now,
          updated_at: now,
        })
        .eq('id', reservation.guest_id)
        .eq('entity_id', reservation.entity_id)

      if (guestError) {
        console.error(`Failed to update guest stats on check-out: ${guestError.message}`)
      }
    }
  }

  // Fire checkout_day automation (best-effort)
  fireAutomationTrigger('checkout_day', {
    organizationId: reservation.entity_id,
    reservationId: reservation.id,
  }).catch(() => {})

  // Log the action
  logAdminAction({
    organizationId: reservation.entity_id,
    action: 'reservation.checkout',
    entityType: 'reservation',
    entityId: reservation.id,
  }).catch(() => {})

  revalidateReservationPaths()
  return reservation
}
